### ISSUE TITLE
Add a config

### ISSUE THREAD

**Issue by neongreen** [wireapp/mls-client#5]
Currently the server address (localhost:10100) is hardcoded. We want to move it to some kind of config that would be read at startup.

**Comment by vytis** [comment]
Maybe simple command line argument would do the job? At the moment there isn't much else to configure...

**Comment by neongreen** [comment]
You'd have to pass it every time you want to run the client, and quite likely you wouldn't want to change it pretty much ever. However, if a CLI argument is easier, that works too.
